### PR TITLE
GUI for N1471H (CAEN)

### PR DESCRIPTION
**Pull request by lobis**

### CODE REVIEW

**Comment by lobis** [comment]
@AlvaroEzq I made some changes to the file:

- Rename to `gui.py` since python files are typically named using `snake_case` notation.
- Add command line argument parsing so the user can specify the serial port (via the `--port` flag). I also added the `--test` flag so it can be used without the serial connection for testing, **however, in order for this to work you need to add your caenSimulator module to the directory**.
- Modify some lambdas in https://github.com/lobis/hvps/pull/63/commits/39669b75c2ec2c980da811dc3a5c25d3e07a24af and https://github.com/lobis/hvps/pull/63/commits/1da155ec35cded0318da0c9d49721cab8d3fab09. I think this is more correct but I am not 100% sure this achieves what you originally intended.

**Comment by AlvaroEzq** [comment]
> however, in order for this to work you need to add your caenSimulator module to the directory.

I added the caenSimulator module in the same directory as gui.py  ([face723](https://github.com/lobis/hvps/pull/63/commits/face723706b33416d0296372642e72205ee0c668)). 

> Modify some lambdas in https://github.com/lobis/hvps/commit/39669b75c2ec2c980da811dc3a5c25d3e07a24af and https://github.com/lobis/hvps/commit/1da155ec35cded0318da0c9d49721cab8d3fab09. I think this is more correct but I am not 100% sure this achieves what you originally intended.

Yes, this achives what I intended :+1:

**Comment by AlvaroEzq** [comment]
The [1231d77](https://github.com/lobis/hvps/pull/63/commits/1231d77c7e40750b107aab4259c12e9c89990c77) breaks the GUI when showing and hiding the ToolTip. Apparently, tkinter sends one extra parameter to the `show_tooltip` and `hide_tooltip`  https://github.com/lobis/hvps/blob/8189ab7fe6125d7a58cb3323605c85adf38653ce/gui/CAEN-N1471H/gui.py#L18-L19 in this lines...

**Comment by lobis** [comment]
> The [1231d77](https://github.com/lobis/hvps/pull/63/commits/1231d77c7e40750b107aab4259c12e9c89990c77) breaks the GUI when showing and hiding the ToolTip. Apparently, tkinter sends one extra parameter to the `show_tooltip` and `hide_tooltip`
> 
> https://github.com/lobis/hvps/blob/8189ab7fe6125d7a58cb3323605c85adf38653ce/gui/CAEN-N1471H/gui.py#L18-L19
> 
> in this lines...

Oh I see. I never use the event variable so it felt strange. Since I don't like to have unused variables (even if they are in fact used behind the scenes by the program) I like to remove them by wrapping the function in a lambda. This should work.

**Comment by lobis** [comment]
@AlvaroEzq when you think this is ready please review and approve the PR (since you are the reviewer) and I'll merge it!

**Review by AlvaroEzq — APPROVED** [review]

**Pull request merged**
